# Generated by Django 5.1.2 on 2024-10-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
