# Generated by Django 5.1.2 on 2024-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
